syntax = "proto3";

package slave_api;

enum DeviceState {
  INIT = 0;
  DISCOVERY_SYNC = 1;
  PRE_OP = 2;
  SAFE_OP = 3;
  OP = 4;
  ERROR = 5;
  SHUTDOWN = 6;
}

enum StatusCode {
  NO_ERROR = 0;
  ERR_PTP_SYNC_LOST = 1;
  ERR_CYCLE_COUNTER = 2;
  ERR_DEADLINE_MISSED = 3;
  ERR_STREAM_ID_UNKNOWN = 4;
  ERR_INVALID_LEN = 5;
  ERR_APP_NOT_RESPONDING = 6;
  ERR_PERIPHERAL_FAULT = 7;
  ERR_NOT_READY = 8;
  ERR_ACCESS_DENIED = 9;
  ERR_AUTH_FAILED = 10;
  ERR_STATE_CONFLICT = 11;
  ERR_PARAM_INVALID = 12;
  ERR_NO_MEMORY = 13;
  ERR_VERSION_MISMATCH = 14;
  ERR_NOT_SUPPORTED = 16;
  ERR_ALREADY_RUNNING = 17;
  ERR_OS_FAILURE = 18;
  ERR_IP_CONFLICT = 19;
  ERR_FRAME_PARSING = 20;
  ERR_FRAME_WITH_ERROR_STATUS = 21;
  ERR_SOCKET_CHANNEL = 22;
  ERR_HARDWARE_ACCESS = 23;
  ERR_TIMEOUT = 24;
  ERR_INVALID_RESPONSE = 25;
}

enum SyncStatus {
  SYNCED = 0; // Error < 1 µs
  SYNCING = 1; // Unstable
  SYNC_LOST = 2; // > Threshold
}

enum LogReason {
  HEARTBEAT = 0;
  STATE_CHANGE = 1;
  STATUS_CODE_CHANGE = 2;
  SYNC_STATUS_CHANGE = 3;
  MISSED_CYCLE = 4;
  TEMPERATURE_CHANGE = 5;
}

enum DataType {
  BOOL = 0; // 1 bit
  INT8 = 1; // 1 byte
  UINT8 = 2; // 1 byte
  INT16 = 3; // 2 bytes
  UINT16 = 4; // 2 bytes
  INT32 = 5; // 4 bytes
  UINT32 = 6; // 4 bytes
  INT64 = 7; // 8 bytes
  UINT64 = 8; // 8 bytes
  FLOAT32 = 9; // 4 bytes (IEEE 754)
  FLOAT64 = 10; // 8 bytes (IEEE 754)
  ARRAY = 11; // Variable length
}

enum Direction {
  INPUT = 0; // Master -> Actuator
  OUTPUT = 1; // Sensor -> Master
}

enum IpSource {
    UNSPECIFIED = 0;
    SDCP = 1;
    DHCP = 2;
    MANUELL = 3;
}

message DeviceInfo {
  bytes mac_address = 1;
  bytes ip_address = 2;
  IpSource ip_source = 3;
  bytes netmask = 4;
  bytes gateway = 5;
  uint32 vendor_id = 6;
  uint32 device_id = 7;
  uint32 serial_number = 8;
  uint32 firmware_version = 9;
  uint32 capabilities = 10;
}

message DeviceStatus {
  StatusCode status_code = 1;
  DeviceState state = 2;
  SyncStatus sync_status = 3;
  uint32 missed_cycles = 4;
  uint32 min_cycle_time = 5;
  uint32 max_cycle_time = 6;
  sint32 temperature = 7;
  uint64 timestamp = 8;
}

message LogEntryDeviceStatus {
  LogReason log_reason = 1;
  DeviceStatus device_status = 2;
}

message ProcessVariable {
  string name = 1;
  DataType data_type = 2;
  Direction direction = 3;
  uint32 byte_offset = 4;
  uint32 bit_offset = 5;
  uint32 bit_len = 6;
}

message Position {
  uint32 byte_offset = 1;
  uint32 bit_offset = 2;
  uint32 bit_len = 3;
}

message StreamConfig {
  uint32 stream_id = 1;
  bytes destination_mac = 2;
  uint32 vlan_id_pcp = 3;
  uint32 cycle_time_nano = 4;
  Direction direction = 5;
  Position stream_content = 6;
}

message Empty {}

message SetTargetStateRequest {
  DeviceState target_state = 1;
}

message ConfigureStreamsRequest {
  repeated StreamConfig streams = 1;
}

message StatusResponse {
  StatusCode code = 1;
}

message SubscribeStatusRequest {
  optional uint32 min_interval_sec = 1;
}

message GetLogRequest {
  uint32 offset = 1;
  uint32 limit = 2;
}

message GetLogResponse {
  uint32 total_entries = 1;
  repeated LogEntryDeviceStatus log_entries = 2;
}

message GetDeviceInfoResponse {
    StatusCode code = 1;
    optional DeviceInfo device_info = 2;
}

message ProcessDataLayoutResponse {
  StatusCode code = 1;
  repeated ProcessVariable variables = 2;
}

message GetTokenRequest {
  bytes shared_key = 1;
}

message GetTokenResponse {
  string token = 1;
  StatusCode status = 2;
}

/// SlaveAPI provides management, configuration, and security operations for the fieldbus slave devices.
/// It allows clients to control device state, monitor status, retrieve logs, process data, and manage authentication.
/// All API endpoints, expect get_token(), are secured through a token based authentication.
service SlaveAPI {
  /// Try to set the state of the device according to the state machine.
  /// Input: Target state.
  /// Output: Status Code, i.e. if the operation was successful or if the state transition was prohibited or there was another error.
  rpc SetTargetState(SetTargetStateRequest) returns (StatusResponse);
  
  /// Get DeviceStatus information.
  /// Input: None.
  /// Output: DeviceStatus information.
  rpc GetStatus(Empty) returns (DeviceStatus);

  /// Subscribe to the DeviceStatus information, i.e. if the DeviceStatus changes, it gets published to the subscribers.
  /// Excluded from the DeviceStatus change publish are the fields min_cycle_time, max_cycle_time, timestamp, because they change to frequently.
  /// The temperature field is acknowledged only after exceeding a threshold.
  /// Input:
  ///   - min_interval_ms: Optional minimal interval at which the DeviceStatus is published even if nothing changed.
  ///                      The value should be greater or equals 10s to prevent flooding of the network. Otherwise, it will be set to a default of 60s.
  ///                      If it isn't supplied the device status is only published on changes.
  /// Output: DeviceStatus information.
  rpc SubscribeToDeviceStatus(SubscribeStatusRequest) returns (stream DeviceStatus);

  /// The DeviceStatus gets loged periodically every 60s and if the status_code, state, sync_state or missed_cycles change.
  /// Furthermore, the log entries get stored in a ring buffer, i.e. if it would exceeds the allocated memory the oldest entry gets replaced.
  /// Input: In the log entry list the newest elements have the lowest indecies.
  ///   - offset: Starting position with 0 the newest entry; 10 would mean to skip the 10 newest entries
  ///   - limit: Number of entries to send with the maximum of 30
  /// Output:
  ///   - total_entries: Number of currently stored entries.
  ///   - log_entries: List of log entries according to the pagination parameters
  rpc GetDeviceStatusLog(GetLogRequest) returns (GetLogResponse);

  /// Get device information.
  /// Input: None.
  /// Output: Device information.
  rpc GetDeviceInfo(Empty) returns (GetDeviceInfoResponse);
  
  /// Get the process data layout, i.e. what data the device can provide or which inputs it has.
  /// Input: None.
  /// Ouput: List of process variables of the device
  rpc GetProcessDataLayout(Empty) returns (ProcessDataLayoutResponse);

  /// Configure L2 streams for cyclic real-time communication.
  /// Valid only in PRE_OP state.
  rpc ConfigureStreams(ConfigureStreamsRequest) returns (StatusResponse);

  /// Get a token to authenticate against the secured API endpoints.
  /// Input:
  ///   - shared_key: Slave key derived from the master key and the serial number of the slave device.
  /// Ouput:
  ///   - token: Valid token if operation successful. Otherwise is this field empty.
  ///   - status_code: Status information in case of an error.
  rpc GetToken(GetTokenRequest) returns (GetTokenResponse);

  /// Reset the sequence number used for the generation of tags in the Hash-based Message Authentication Code (HMAC)
  rpc ResetSequenceNumber(Empty) returns (StatusResponse);
}
