[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
default = []
test-utils = []

[dependencies]
# Serialization and Error handling
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.5"
thiserror = "1.0"

# gRPC Runtime Dependencies
tonic = "0.12"
prost = "0.13"

pnet = "0.35"

[build-dependencies]
tonic-build = "0.12"
protobuf-src = "1.1"
